version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: node:9.11
        environment:
          DEPLOY_BRANCH: master

    steps:
      - checkout

      - run:
          name: Deploy development branch to master
          command: |
            if [ "${CIRCLE_BRANCH}" = "${DEPLOY_BRANCH}" ]; then
              cd ../
              mkdir work2
              cp work/deploy.sh work2/.
              chmod +x work2/deploy.sh
              cd work
              ../work2/deploy.sh
            fi